@startuml
skinparam shadowing false

(*) --> ===b1===
--> "build-backend"
--> "test-backend"
--> ===b2===

===b1=== --> "build-frontend"
--> "test-frontend"
--> ===b2===

--> "integration"
--> "docker"
--> (*)

@enduml

