@startuml frontend_plot_selection

participant "ScatterPlotComponent" as spc
participant "PlotService" as dp
participant ":Database\nController" as db

[-> spc ++: ngOnInit()
spc -> spc ++: parseQueryParameters()

spc -> dp ++: generateScatterPlot()
return data:BubbleChartMultiSeries

return void;


dp -> db ++: insert(cleanData)
return status:Status

return status:Status

spc -> spc ++: composeResponse(status)
return responseCode:HttpStatus

[<-- spc --: request.response(responseCode)
note left: Indicates POST\nsuccess/failure


@enduml