@startuml backend

skinparam linetype ortho

package git {
  interface History {
   BranchForBenchmark getBranch(branch: String, benchmark: Benchmark)
  }

  interface RepositoryHandler {
    BranchForBenchmark fetchGitHistory(branch: String)
  }

  class CachingHistoryDecorator {
    component: GitHistory
    List<Branch>: lastUsedBranches
  }
  class Commit {
    previousCommit: Commit
    sha: String
    message: String
    date: java.util.Date
    benchmarkResultsByDevice: Map<Device, BenchmarkResult>
    String getCommitMessage()
    String getSha()
    BenchmarkResult getBenchmarkResult(device: Device)
    Commit getPreviousCommit()
  }
  
  
  class BranchForBenchmark {
    name: String
    benchmark: Benchmark
    commits: List<Commit>
    Commit getCommit(sha: String)
    List<Commit> toList()
  }
    
  interface BenchmarkResult {
    Commit getCommit()
    String getBenchmarkName()
    Device getDevice()
    String toJson()
    double getSummaryValue()
  }

  class Benchmark {
    # TODO add fields for other info
    name: String
  }

  class Device {
    # TODO add fields for other info
    name: String
  }

  class EmptyBenchmarkResult
  EmptyBenchmarkResult --|> BenchmarkResult
  
  History o-- BranchForBenchmark
  History --> RepositoryHandler
  History <|-- CachingHistoryDecorator
  History --o CachingHistoryDecorator
  
  BranchForBenchmark o-- Commit
  Commit "1" -- "*" BenchmarkResult
}


package rest {
  class GitApiHandler
  class SpringRestHandler
  
  interface RestHandler {
    void handlePost(json: String)
    void handleGetHistory(json: String)
    void handleGetBenchmarkResult(json: String)
  }
   
  SpringRestHandler --|> RestHandler
}

package database {
  class PostgreSQLHandler
  
  interface DatabaseHandler {
    void updateCommits(commits: List<Commit>)
    void updateBenchmarkResults(results: List<BenchmarkResult>)
    BranchForBenchmark fetchBranch(branch: String, benchmark: Benchmark)
    Commit fetchSinlgeCommit(sha: String)
    BenchmarkResult fetchSingleBenchmarkResult(commit: Commit, device: Device, benchmark: Benchmark)
  }
  
  class HistoryDatabase
  
  DatabaseHandler <- HistoryDatabase
  DatabaseHandler <|-- PostgreSQLHandler

  class BenchmarkResultDatabase
  
  DatabaseHandler <- BenchmarkResultDatabase
  
  class LazyBenchmarkResult {
    component: BenchmarkResult
  }

  DatabaseHandler <-- LazyBenchmarkResult
}

package processing {
  interface RawBenchmarkResult {
    BenchmarkResult process()
  } 

  class RawBenchmarkResultTypeA

  class DataProcessor {
    void storeBenchmarkResults(results: List<RawBenchmarkResult>)
  }

  interface BenchmarkResultStorage {
    void storeBenchmarkResults(results: List<BenchmarkResult>)
  }

  class BenchmarkResultTypeA

  RawBenchmarkResult <- DataProcessor
  BenchmarkResultStorage <- DataProcessor
  RawBenchmarkResult <|-- RawBenchmarkResultTypeA
  RawBenchmarkResultTypeA -> BenchmarkResultTypeA: "process()"
}

History <- RestHandler
History <|- HistoryDatabase
BenchmarkResultStorage <|- BenchmarkResultDatabase
RepositoryHandler <|- GitApiHandler
DatabaseHandler -> Commit
DatabaseHandler -> BenchmarkResult
HistoryDatabase -> BranchForBenchmark
BenchmarkResult <|- BenchmarkResultTypeA
BenchmarkResult <|- LazyBenchmarkResult
BenchmarkResult <- LazyBenchmarkResult
BenchmarkResult <- RawBenchmarkResult
DataProcessor <- RestHandler

@enduml
