@startuml backend

skinparam linetype ortho

package git {
  interface History {
    Branch getBranch(branch: String, device: String, benchmark: String)
  }

  interface RepositoryHandler {
    List<Commit> fetchGitHistory()
  }

  class CachingDecorator {
    component: GitHistory
    List<Branch>: lastUsedBranches
  }
  
  class Commit {
    sha: String
    message: String
    date: java.util.Date
    benchmarkResult: BenchmarkResult
    String getCommitMessage()
    String getSha()
    String getDiff() or smth like that?
    BenchmarkResult getBenchmarResult()
  }
  
  
  class Branch {
    name: String
    device: String
    benchmark: String
    commits: List<Commit>
    Commit getCommit(sha: String)
    List<Commit> toList()
  }
    
  abstract BenchmarkResult {
    smth getData()
    String toJson()
    double getSummaryValue()
  }
  
  
  class BenchmarkResultTypeA
  class BenchmarkResultTypeB
  
  
  BenchmarkResult <|-- BenchmarkResultTypeA
  BenchmarkResult <|-- BenchmarkResultTypeB
  
  History o-- Branch
  History --> RepositoryHandler
  History <|-- CachingDecorator
  History o-- CachingDecorator
  
  Branch o-- Commit
  Commit "1" -- "1" BenchmarkResult
}


package rest {
  class GitApiHandler
  class SpringRestHandler
  
  interface RestHandler {
    void handlePost(smth: json)
    void handleGet(smth: json)
  }
   
  SpringRestHandler --|> RestHandler
}

package database {
  class PostgreSQLHandler
  
  interface DatabaseHandler {
    void updateCommits(commits: List<Commit>)
    void updateBenchmarkResults(results: List<BenchmarkResult>)
  }
  
  DatabaseHandler <- HistoryDatabase
  DatabaseHandler <|-- PostgreSQLHandler
  
  class HistoryDatabase {
    Branch getBranch(branch: String, device: String, benchmark: String)
  }
}

History <--- RestHandler
History <|--- HistoryDatabase
RepositoryHandler <|--- GitApiHandler
DatabaseHandler ---> Commit
DatabaseHandler ---> BenchmarkResult
HistoryDatabase ---> Branch
@enduml
