@startuml FR1

box "Frontend"
actor ":User:" as ted
participant ":GUI" as gui
participant ":GuiHandler" as gh
participant ":DatapointSelection" as selection
participant ":DataHandler" as dh
end box

box "Backend"
participant ":RestHandler" as rh
participant ":GitHistory" as ghist
participant ":DatabaseHandler" as datah
end box

participant ":Git Api" as gitapi

ted -> gui ++: opens

gui -> gh ++: updateView()
gh -> dh ++: getCommitHistory(branch: String, device: String, benchmark: String)
dh -> rh ++: get request for commit history
rh -> ghist ++: getCommitHistory(branch: String, device: String, benchmark: String)

alt git history is not up to date
  ghist -> rh ++: fetchGitHistory()
  rh -> gitapi ++: get request for history
  gitapi --> rh --: commits: List<Commit>
  rh --> ghist --: commits: List<Commit>
  ghist -> datah ++: updateHistory(commits: List<Commit>)
  datah --> ghist --:
  end

ghist -> datah ++: getHistory()
datah --> ghist --: history: List<Commit>

ghist --> rh --: history: List<Commit>
rh --> dh --: commit history
dh --> gh --: List<Commit>
gh --> gui --:



ted -> gui: selects a datapoint
gui -> gh ++: selectDatapoint(benchmark: String, branch: String, device: String, commit: String)

alt first selected datapoint
  create selection
  gh -> selection : DatapointSelection()
  end

gh -> selection ++: addDatapoint(datapoint: DataPoint)
selection --> gh --:
gh --> gui --:
gui --> ted --:

@enduml
