@startuml fr4

skinparam responseMessageBelowArrow true

participant ":RestHandler" as rh
participant ":DataProcessor" as dp
participant ":Database\nController" as db


-> rh ++: POST request
note left: contains benchmark results

rh -> dp ++: process(jsonData)
dp -> dp ++: format(jsonData)
dp --> dp --: cleanData:FormattedData

note right: Put data into correct\nformat for database

dp -> db ++: insert(cleanData)
db --> dp --: status:Status
dp --> rh --: status:Status
rh -> rh ++: composeResponse(status)
rh <-- rh --: responseCode:HttpStatus

<-- rh --: request.response(responseCode)
note left: Indicates POST\nsuccess/failure

@enduml
