@startuml

left to right direction

skinparam linetype ortho
skinparam shadowing false
skinparam dpi 300
skinparam backgroundColor transparent

skinparam activity {
    ArrowColor #2E3440
    BarColor #2E3440
    EndColor #2E3440
    StartColor #2E3440
    BackgroundColor #5E81AC
    FontColor #ECEFF4
    BorderColor transparent
}

(*) --> ===b1===
--> "build-backend"
--> "test-backend"
--> ===b2===

===b1=== --> "build-frontend"
--> "test-frontend"
--> ===b2===

===b1=== --> "analyze-backend"
===b1=== --> "analyze-frontend"

===b2=== --> "integration"
--> "docker"
--> (*)

@enduml
